modLoader = "kotlinforforge"
loaderVersion = "[${versions.kotlin_forge},)"
license = "MIT"

[[mods]]
modId = "hcaddon"
version = "${version}"
displayName = "HCAddon"
logoFile = "assets/hcaddon/icon.png"
authors = "Custom-Coder"
description = "HCAddon addon for Hex Casting"

[[dependencies.hcaddon]]
modId = "forge"
mandatory = true
versionRange = "[${versions.forge_dependency},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hcaddon]]
modId = "minecraft"
mandatory = true
versionRange = "[${versions.minecraft},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hcaddon]]
modId = "architectury"
mandatory = true
versionRange = "[${versions.architectury},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hcaddon]]
modId = "cloth_config"
mandatory = true
versionRange = "[${versions.cloth_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hcaddon]]
modId = "hexcasting"
mandatory = true
versionRange = "[${versions.hexcasting_dependency},)"
ordering = "NONE"
side = "BOTH"
